### PR TITLE
gff

### PR DESCRIPTION
**Pull request by j23414**
* re-added the bad-0 raw block and added the bad-1 raw block
- seems to be missing the summary block of text, not sure if my old push got deleted or if it was taken out

### CODE REVIEW

**Comment by arendsee** [comment]
Yeah, sorry about that, but have been lost

**Comment by j23414** [comment]
No worries, I assume it's cause I did a delete and re-fork. 

Btw, are you working on the JOSS figure? I read through the text but couldn't figure out what I should work on...any suggestions?

**Comment by arendsee** [comment]
Yeah, I've done some sketching of a possible figure, but I don't have an electronic version yet.

I think the confusion in git comes from pushing to different repos. I've been doing all my work on the dev branch. But your pull requests were to master. That's my fault; I don't think I explained properly what goes where.

I suppose it is alright, though, for us to work on master. Most github repos have a dev and master branch, where master is always a release version. But for R packages, CRAN serves as the official release version and github master is more like a dev branch. Also, as long as we aren't making radical changes (where we might want to just kill the whole branch if things go sour), pushing everything to one branch is probably simpler.

As for what to work on, let me go back and reread the paper and get back to you in a bit.

**Comment by arendsee** [comment]
Actually, let's just jump over to Google chat

**Pull request merged**
